################################################################################
# Plotting Script for GNAR Spectrum Results
# ------------------------------------------------------------------------------
# This script produces the coherence and partial coherence plots based on the
# results generated by the file "r-gnar-spec.R".
#
# Author: Cristian Felipe Jimenez Varon
# University of York, Department of Mathematics
# Date: October 2025
################################################################################

# -------------------------------
# SETUP
# -------------------------------
library(igraph)
library(GNAR)
library(abind)
library(ggplot2)
library(reshape2)
library(patchwork)

# Directories
dir.mac <- "~/Library/CloudStorage/GoogleDrive-cristian.jimenezvaron@york.ac.uk/My Drive/2024/York/"
dir <- dir.mac
setwd(file.path(dir, "Rcodes"))

dir.r <- file.path(dir, "Results/")
dir.p <- file.path(dir, "Plots_paper_spec/")

# Helper function to save plots
save_plot <- function(filename, plot_obj) {
  pdf(file = file.path(dir.p, filename), width = 8, height = 6)
  print(plot_obj)
  dev.off()
}

# -------------------------------
# LOAD DATA
# -------------------------------
sft_spec_gnar_est <- readRDS(file.path(dir.r, "sft_spectrum_GNAR_est_new.rds"))
True <- readRDS(file.path(dir.r, "True_gnar_spec.rds"))

# Configuration
dataset_list <- c(4)   # Use dataset index 4
sim_idx <- 1           # Use first simulation
r_star <- 3

n_models <- length(True[[1]])
n_nodes <- dim(True[[1]][[1]])[1]

# -------------------------------
# MAIN COMPUTATION LOOP
# -------------------------------
results_list <- list()

for (dataset_idx in dataset_list) {
  cat("Dataset T =", dataset_idx, "\n")
  n_freqs <- dim(True[[dataset_idx]][[1]])[3]
  results_list[[paste0("Dataset_", dataset_idx)]] <- list()
  
  for (model_idx in seq_len(n_models)) {
    cat("  Model", model_idx, "\n")
    
    true_spec <- True[[dataset_idx]][[model_idx]]
    
    # Inverse of true spectrum for all frequencies
    true_inv_spec <- array(NA, dim = dim(true_spec))
    for (f in 1:n_freqs) {
      true_inv_spec[,,f] <- solve(true_spec[,,f])
    }
    
    model_results <- list()
    r_star_model <- min(model_idx, 3)
    
    for (r_level in seq_len(r_star_model)) {
      cat("    r =", r_level, "\n")
      
      est_spectrum <- sft_spec_gnar_est[[dataset_idx]][[model_idx]][[sim_idx]][[2]][[r_level]]
      est_inv_spec <- sft_spec_gnar_est[[dataset_idx]][[model_idx]][[sim_idx]][[1]][[r_level]]
      
      # Storage structure
      model_results[[paste0("r", r_level)]] <- list(
        spectrum = list(true = true_spec, est = est_spectrum),
        coherence = list(),
        partial_coherence = list()
      )
      
      # --- Coherence ---
      coh_true <- coh_est <- array(0, dim = c(n_nodes, n_nodes, n_freqs))
      for (f in 1:n_freqs) {
        for (i in 1:n_nodes) {
          for (j in 1:n_nodes) {
            if (i != j) {
              Sii_true <- Re(true_spec[i, i, f])
              Sjj_true <- Re(true_spec[j, j, f])
              Sii_est  <- Re(est_spectrum[i, i, f])
              Sjj_est  <- Re(est_spectrum[j, j, f])
              
              coh_true[i, j, f] <- Mod(true_spec[i, j, f])^2 / (Sii_true * Sjj_true)
              coh_est[i, j, f]  <- Mod(est_spectrum[i, j, f])^2 / (Sii_est * Sjj_est)
            }
          }
        }
      }
      model_results[[paste0("r", r_level)]]$coherence <- list(true = coh_true, est = coh_est)
      
      # --- Partial Coherence ---
      pcoh_true <- pcoh_est <- array(0, dim = c(n_nodes, n_nodes, n_freqs))
      for (f in 1:n_freqs) {
        G_true <- true_inv_spec[,,f]
        G_est  <- est_inv_spec[,,f]
        
        D_true <- diag(1 / sqrt(abs(Re(diag(G_true)))))
        D_est  <- diag(1 / sqrt(abs(Re(diag(G_est)))))
        
        Gamma_true <- -D_true %*% G_true %*% D_true
        Gamma_est  <- -D_est  %*% G_est  %*% D_est
        
        pcoh_true[,,f] <- Mod(Gamma_true)^2
        pcoh_est[,,f]  <- Mod(Gamma_est)^2
      }
      model_results[[paste0("r", r_level)]]$partial_coherence <- list(true = pcoh_true, est = pcoh_est)
    }
    
    results_list[[paste0("Dataset_", dataset_idx)]][[paste0("Model_", model_idx)]] <- model_results
  }
}

# -------------------------------
# PLOTTING FUNCTION
# -------------------------------
plot_multiple_pairs <- function(data_model_list, 
                                pairs_models,
                                type = c("coherence", "partial_coherence"),
                                r = 1,
                                save = FALSE, 
                                save_dir = NULL,
                                save_filename = "combined_plot.pdf") {
  
  type <- match.arg(type)
  est_colors <- true_colors <- c("blue", "red", "green")
  
  est_curves <- list()
  true_curves <- list()
  all_values <- c()
  freq_len <- NULL
  freqs <- NULL
  
  for (i in seq_along(pairs_models)) {
    pair <- pairs_models[[i]]
    model_num <- pair$model
    data_model <- data_model_list[[as.character(model_num)]]
    
    est_matrix <- data_model[[paste0("r", r)]][[type]]$est
    true_matrix <- data_model[[paste0("r", model_num)]][[type]]$true
    
    if (is.null(freq_len)) {
      freq_len <- dim(est_matrix)[3]
      freqs <- seq(0, 0.5, length.out = freq_len)
    }
    
    est_values <- est_matrix[pair$node1, pair$node2, ]
    true_values <- true_matrix[pair$node1, pair$node2, ]
    
    est_curves[[i]] <- est_values
    true_curves[[i]] <- true_values
    all_values <- c(all_values, est_values, true_values)
  }
  
  ylim_range <- range(all_values, na.rm = TRUE)
  ylim_range <- ylim_range + c(-0.05, 0.05) * diff(ylim_range)
  
  if (save) {
    if (is.null(save_dir)) stop("Please provide save_dir if save=TRUE")
    if (!dir.exists(save_dir)) dir.create(save_dir, recursive = TRUE)
    pdf(file.path(save_dir, save_filename), width = 10, height = 8)
    par(cex = 1.2, cex.axis = 1.4, cex.lab = 1.4)
  }
  
  plot(freqs, est_curves[[1]], type = "n",
       ylim = ylim_range,
       xlab = "Frequency",
       ylab = ifelse(type == "partial_coherence", "Partial Coherence", "Coherence"),
       lwd = 2)
  
  for (i in seq_along(pairs_models)) {
    lines(freqs, est_curves[[i]], col = est_colors[i], lwd = 3, lty = 1)
    lines(freqs, true_curves[[i]], col = true_colors[i], lwd = 3, lty = 2)
  }
  
  legend_labels <- c()
  legend_colors <- c()
  legend_lty <- c()
  
  for (i in seq_along(pairs_models)) {
    pair <- pairs_models[[i]]
    legend_labels <- c(legend_labels,
                       paste0("Est: Node ", pair$node1, "-", pair$node2, " (Model ", pair$model, ")"),
                       paste0("True: Node ", pair$node1, "-", pair$node2, " (Model ", pair$model, ")"))
    legend_colors <- c(legend_colors, est_colors[i], true_colors[i])
    legend_lty <- c(legend_lty, 1, 2)
  }
  
  legend("topright", legend = legend_labels,
         col = legend_colors, lty = legend_lty, lwd = 3, cex = 1.2,
         bg = "white", box.lwd = 0.7)
  
  if (save) dev.off()
}

# -------------------------------
# EXAMPLES: PLOT AND SAVE
# -------------------------------
data_models_list <- list(
  "1" = results_list$Dataset_4$Model_3,
  "2" = results_list$Dataset_4$Model_3,
  "3" = results_list$Dataset_4$Model_3
)

pairs_models <- list(
  list(node1 = 1, node2 = 8, model = 3),
  list(node1 = 1, node2 = 4, model = 3),
  list(node1 = 1, node2 = 2, model = 3)
)

# Preview plots (not saved)
for (r_level in 1:3) {
  plot_multiple_pairs(data_models_list, pairs_models, "coherence", r = r_level, save = FALSE)
  plot_multiple_pairs(data_models_list, pairs_models, "partial_coherence", r = r_level, save = FALSE)
}

# Save final plots
for (r_level in 1:3) {
  plot_multiple_pairs(
    data_models_list, pairs_models,
    "coherence", r = r_level, save = TRUE,
    save_dir = dir.p, save_filename = paste0("coherence_r", r_level, ".pdf")
  )
  plot_multiple_pairs(
    data_models_list, pairs_models,
    "partial_coherence", r = r_level, save = TRUE,
    save_dir = dir.p, save_filename = paste0("partial_coherence_r", r_level, ".pdf")
  )
}
